# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c02329e93558cf159ea068d5812cf701530aa1b45ace0fa12734e2509ddaa682ae025ee7125be188e69a428ef42239316f4d8129ed22509768666de98881ee9

test:
  secret_key_base: 271a906eeb669b1c660cadc846072a438d994e210bb38ad5c937900d19676295978249d8fab72a63f5ec719e40f3f3c648c363d3d071dfdca7cd7a15244dd5be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
